name: ftpclient
description: A simple dart FTP Client
version: 0.2.0
homepage: https://nexific.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  path: ^1.6.4

dev_dependencies:
  test: ^1.6.0
